name: "Custom GitHub Script"
description: "A custom action to run a GitHub script with @octokit/auth-app"
runs:
  using: "node20"
  main: "index.js"
# inputs:
  # github-token:
  #   description: "GitHub Token"
  #   required: true
  # app-id:
  #   description: "GitHub App ID"
  #   required: true
  # installation-id:
  #   description: "GitHub App Installation ID"
  #   required: true
  # private-key:
  #   description: "GitHub App Private Key"
  #   required: true
  # repo:
  #   description: "Repository"
  #   required: true
  #   default: 'state'
  # branch:
  #   description: "Branch"
  #   required: true
  #   default: 'main'
  # path:
  #   description: "Path"
  #   required: true
  #   default: './state.json'
  # message:
  #   description: "Message"
  #   required: true
  #   default: 'chore: update state'
  # content:
  #   description: "Content"
  #   required: true
  #   default: 'state'
  