name: "Run Composite Action"
description: "A custom action to run a composite action"
inputs:
  repo:
    description: "Repository"
    required: false
    default: 'state'

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        echo "Installing dependencies..."
    - name: print all context available
      shell: bash
      env:
        DEBUG: ${{ toJson(github) }}
      run: |
        echo $DEBUG

