name: "Run Composite Action"
description: "A custom action to run a composite action"
inputs:
  action:
    description: "what action to run: init, end, send"
    required: false
    default: 'init'


runs:
  using: "composite"
  steps:
    
    - name: Get time of initialization
      id: init
      shell: bash
      run: |
        echo "${{ github.job }}" 
        echo "date=$(date)" 
        echo "job-id=${{ github.job }}" >> $GITHUB_OUTPUT
        echo "job-init=$(date)" >> $GITHUB_OUTPUT
    - name: Get time of end
      id: end
      shell: bash
      run: |
        echo "${{ github.job }}" 
        echo "date=$(date)" 
        echo "job-id=${{ github.job }}" >> $GITHUB_OUTPUT
        echo "job-end=$(date)" >> $GITHUB_OUTPUT
    - name: Send time to GitHub
      id: send
      shell: bash
      run: |
        echo "## ${{ github.job }} metrics" >> $GITHUB_STEP_SUMMARY 
        # echo "" >> $GITHUB_STEP_SUMMARY
        # echo "job-init= ${{ steps.init }}" >> $GITHUB_STEP_SUMMARY
        # echo "job-end= ${{ steps.end }}" >> $GITHUB_STEP_SUMMARY


