name: "retrive Metrics"
description: "A custom action to run a composite action"
inputs:
  action:
    description: "what action to run: init, end, send"
    required: false
    default: 'init'
outputs:
  job-init:
    description: "Initialization job output"
    value: ${{ steps.init.outputs.job-init }}
  job-end:
    description: "End job output"
    value: ${{ steps.end.outputs.job-end }}



runs:
  using: "composite"
  steps:
    - name: Cache values
      id: cache-metrics
  
      uses: actions/cache@v4
      with:
        path: ${{ github.job }}-metrics
        key: ${{ github.job }}-metrics
        restore-keys: ${{ github.job }}-metrics


    - name: Get time of initialization
      id: init
      if: ${{ inputs.action == 'init'  }}
      
      shell: bash
      run: |
        echo "job-id=${{ github.job }} init" >> $GITHUB_OUTPUT
        echo "job-init=$(date)" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT >> ./${{ github.job }}-metrics


    # - name:

    - name: sleep 5
      shell: bash
      run: sleep 5
    - name: Get time of end
      id: end
      if: ${{ inputs.action == 'end' }}
      shell: bash
      run: |

        echo "job-id=${{ github.job }} end" >> $GITHUB_OUTPUT
        echo "job-end=$(date)" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT >> ./${{ github.job }}-metrics

    # - name: Send time to GitHub
    #   id: send
    #   shell: bash
    #   run: |
    #     echo "## ${{ github.job }} metrics ${{inputs.action}}" > $GITHUB_STEP_SUMMARY 
    #     echo "" >> $GITHUB_STEP_SUMMARY
    #     echo "----" >> $GITHUB_STEP_SUMMARY


