name: "Run Composite Action"
description: "A custom action to run a composite action"
inputs:
  action:
    description: "what action to run: init, end, send"
    required: false
    default: 'init'


runs:
  using: "composite"
  steps:
    
    - name: Get time of initialization
      id: init
      
      shell: bash
      run: |
        echo "${{ github.job }}" 
        echo "job-id=${{ github.job }}" >> $GITHUB_OUTPUT
