name: "retrive Metrics"
description: "A custom action to run a composite action"
inputs:
  action:
    description: "what action to run: init, end, send"
    required: false
    default: 'init'
runs:
  using: "composite"
  steps:
    - name: Cache values
      id: cache-metrics
      uses: actions/cache@v4
      with:
        path: cache-metrics
        key: ${{ github.job }}-metrics

    - name: Get time of initialization
      id: init
      if: ${{ inputs.action == 'init' }}
      shell: bash
      run: |
        echo "${{ github.job }}" 
        echo "date=$(date)" 
        echo "job-id=${{ github.job }}" >> $GITHUB_OUTPUT
        echo "job-init=$(date)" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT



    # - name:

    - name: sleep 5
      shell: bash
      run: sleep 5
    - name: Get time of end
      id: end
      if: ${{ inputs.action == 'end' }}
      shell: bash
      run: |
        echo "${{ github.job }}" 
        echo "date=$(date)" 
        echo "job-id=${{ github.job }}" >> $GITHUB_OUTPUT
        echo "job-end=$(date)" >> $GITHUB_OUTPUT
    - name: Send time to GitHub
      id: send
      shell: bash
      run: |
        echo "## ${{ github.job }} metrics" >> $GITHUB_STEP_SUMMARY 
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "job-init= ${{ steps.init.outputs.job-init }}" >> $GITHUB_STEP_SUMMARY
        echo "job-end= ${{ steps.end.outputs.job-end }}" >> $GITHUB_STEP_SUMMARY


