name:  GitHub App Composite Action 
description: "A custom action to run a composite action"
inputs:
  action:
    description: "What action to run: init, end, send"
    required: false
    default: 'init'
  app-id:
    description: "GitHub App ID"
    required: true
  installation-id:
    description: "GitHub App ID"
    required: true
  private-key:
    description: "GitHub App Private Key"
    required: true
runs:
  using: "node20"
  main: "index.js"
  # repo:
  #   description: "Repository"
  #   required: true
  #   default: 'state'
  # branch:
  #   description: "Branch"
  #   required: true
  #   default: 'main'
  # path:
  #   description: "Path"
  #   required: true
  #   default: './state.json'
  # message:
  #   description: "Message"
  #   required: true
  #   default: 'chore: update state'
  # content:
  #   description: "Content"
  #   required: true
  #   default: 'state'
  