name: 'Workflow of manager flows'

on:
  push:
    branches:
      - main
      - release/*
      - develop
      - hotfix/*
      - feature/*

  workflow_dispatch:
    inputs:
      is-act:
        description: 'Is this an act?'
        required: true
        default: 'false'

jobs:
  tagger:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag-type: ['patch']
        # tag-type: ['patch', 'minor', 'major', 'stable']

    outputs:
      is-act: ${{ steps.vars.outputs.IS_AC }}
    steps:
        - name:  Checkout code
          uses: actions/checkout@v4
          with:
            fetch-tags: 0
            fetch-depth: 0
        - name: Retrieve app token
          id: app-token
          uses: ./.github/actions/gh-app-script
          with:
            app-id: ${{ secrets.GH_APP_ID }}
            private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
            installation-id: ${{ secrets.GH_APP_INSTALLATION_ID }}
        - name: patch version
          id: patch-verision
          if: ${{ matrix.tag-type == 'patch' }}
          uses: ./.github/actions/semmantic-version
          with:
            tag-type: ${{ matrix.tag-type }}
            token: ${{ steps.app-token.outputs.token }}
  
        - name: minor version
          id: minor-verision
          if: ${{ matrix.tag-type == 'minor' }}
          uses: ./.github/actions/semmantic-version
          with:
            tag-type: ${{ matrix.tag-type }}
            token: ${{ steps.app-token.outputs.token }}
  
        - name: patch version
          id: major-verision
          if: ${{ matrix.tag-type == 'major' }}
          uses: ./.github/actions/semmantic-version
          with:
            tag-type: ${{ matrix.tag-type }}
            token: ${{ steps.app-token.outputs.token }}
  
        - name: stable version
          id: stable-verision
          if: ${{ matrix.tag-type == 'stable' }}
          uses: ./.github/actions/semmantic-version
          with:
            tag-type: ${{ matrix.tag-type }}
            token: ${{ steps.app-token.outputs.token }}
  

