name: My-Subworkflow-gh

on:
  push:
    tags:
      - gh*
  #   branches:
  #     - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh
      - name: Authenticate GitHub CLI
        run: |
          echo ${{ secrets }} 
          echo ${{ secrets.TOKEN }} | gh auth login --with-token
      - name: install gh copilot extension
        run: |
          gh extension install github/gh-copilot
      - name: Explain gh copilot
        run: |
          gh repo list --limit 100
          gh copilot explain "sudo apt-get"
      - name: Build and deploy
        run: |
          # Add your build and deploy commands here
          echo "Build and deploy complete"
 