name: Update Minor Version on Release

on:
  push:
    branches:
      - release

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the latest tag
        id: get_tag
        run: |
          # Fetch all tags
          git fetch --tags

          # Get the latest tag or set default
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")

          # Split the latest tag into components
          IFS='.' read -r major minor patch <<<"${latest_tag#v}"

          # Increment the minor version and reset patch version
          minor=$((minor + 1))
          patch=0

          # Create the new tag
          new_tag="v${major}.${minor}.${patch}"
          
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Tag the commit
        run: |
          git tag ${{ env.new_tag }}

      - name: Push the new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin ${{ env.new_tag }}
