name: scheduled workflows

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight - diario
    - cron: '0 0 * * 0' # every sunday at midnight - semanal
    - cron: '0 0 15 * *' # every 15th day of the month at midnight - quinzenal
    - cron: '0 0 28-31 * *' # every last day of the month at midnight - quinzenal
    - cron: '0 0 1 * *' # every first day of the month at midnight - mensal
    - cron: '0 0 1,3,5,7,9,11 * *' # every first day of the month at midnight - bimestral
    - cron: '0 0 1,4,7,10 * *' # every first day of the month at midnight - trimestral
    - cron: '0 0 1,7 * *' # every first day of the month at midnight - semestral


    
jobs:
  scheduled-workflows:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Run scheduled workflow for diario
        if: github.event_name == '0 0 * * *'
        run: |
            echo "Running scheduled workflow for diario"
            echo "This workflow runs every day at midnight"
      - name: Run scheduled workflow for semanal
        if: github.event_name == '0 0 * * 0'
        run: |
            echo "Running scheduled workflow for semanal"
            echo "This workflow runs every day at midnight"
      - name: Run scheduled workflow for quinzenal
        if: github.event_name == '0 0 15 * *' || github.event_name == '0 0 28-31 * *'
        run: |
            echo "Running scheduled workflow for quinzenal"
            echo "This workflow runs every day at midnight"
      - name: Run scheduled workflow for mensal
        if: github.event_name == '0 0 1 * *'
        run: |
            echo "Running scheduled workflow for mensal"
            echo "This workflow runs every day at midnight"
      - name: Run scheduled workflow for bimestral
        if: github.event_name == '0 0 1,3,5,7,9,11 * *'
        run: |
            echo "Running scheduled workflow for bimestral"
            echo "This workflow runs every day at midnight"
      - name: Run scheduled workflow for trimestral
        if: github.event_name == '0 0 1,4,7,10 * *'
        run: |
            echo "Running scheduled workflow for trimestral"
            echo "This workflow runs every day at midnight"
      - name: Run scheduled workflow for semestral
        if: github.event_name == '0 0 1,7 * *'
        run: |
            echo "Running scheduled workflow for semestral"
            echo "This workflow runs every day at midnight"

 
