name: Tag Commit on Develop 

on:
  push:
    branches:
      -  main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Get the latest tag
        id: get_tag
        run: |
          # Fetch all tags
          git fetch --tags
          git pull --tags

          echo '------'
          echo $(git tag -l)
          echo '------'

          # Get the latest tag
          latest_tag=$(git tag -l|| echo "v0.0.0")

          echo "latest_tag=$latest_tag"


          
          # Split the latest tag into components
          IFS='.' read -r major minor patch <<<"${latest_tag#v}"

          echo "major=$major"
          echo "minor=$minor" 
          echo "patch=$patch" 

          # Increment the patch version
          patch=$((patch + 1))
          echo "patch=$patch" 

          # Create the new tag
          new_tag="v${major}.${minor}.${patch}"
          
          echo "new_tag=$new_tag" >> $GITHUB_ENV
          echo "new_tag=$new_tag"

      - name: Tag the commit
        run: |
          git tag ${{ env.new_tag }}

      - name: Push the tag
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git push origin ${{ env.new_tag }}