name: GH-APP-WORKFLOWs
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}


on:
  push:
    tags:
      - v0.0.*
    branches:
      - main
    
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: 'The name of the image'
        required: true
        default: 'my-image'
      PEM:
        description: 'The private key for the GitHub App'
        required: true
      APP_ID:
        description: 'The ID of the GitHub App'
        required: true
      INSTALLATION_ID:
        description: 'The ID of the GitHub App installation'
        required: true
      MAIN_BRANCH:
        description: 'The main branch of the repository'
        required: true
        default: 'main'

env:
  IMAGE_NAME: ${{ github.repository }}
  TOKEN: ${{ secrets.TOKEN }}
  MAIN_BRANCH: ${{ secrets.MAIN_BRANCH }}
  GH_APP_ID: ${{ secrets.GH_APP_ID }}
  GH_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
  GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
  GH_APP_PRIVATE_KEY_PATH: ${{ secrets.GH_APP_PRIVATE_KEY_PATH }}
  GH_APP_CLIENT_ID: ${{ secrets.GH_APP_CLIENT_ID }}
  GH_APP_CLIENT_SECRET: ${{ secrets.GH_APP_CLIENT_SECRET }}
  





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v3
        with:
          repository: 'IanOliv/state'
          ref: 'src'
          token: ${{ secrets.TOKEN }}
          path: ./state
      - name: List repository files
        uses: ./.github/actions/gh-app-script
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          app-id: ${{ secrets.APP_ID }}
          installation-id: ${{ secrets.INSTALLATION_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/github-script@v7
        id: my-script
        with:
          github-token: ${{ secrets.TOKEN }}
          result-encoding: string
          retries: 3
          retry-exempt-status-codes: 400,401
          script: |

            console.log(`-----process env-----`);
            console.log(process.env);
            console.log(`-----process env-----`);

            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const path = ''; // Root directory, change this to list files in a specific directory
            console.log(`Files in ${owner}`);
            console.log(`Files in ${repo} `);
            console.log(`Files in  ${path}`);

            console.log(`-----workflow inputs-----`);
            console.log(JSON.stringify(github, null, 2));
            console.log(JSON.stringify(context, null, 2));
            console.log(`-----workflow inputs-----`);


            const { data: files } = await github.rest.repos.getContent({
              owner,
              repo:'state',
              path
            });

            for (const file of files) {
              console.log(`- ${file.name}`);
            }
# uses: actions/github-script@v7
#   id: my-script
          
# const octokit = new Octokit({
#   auth: 'YOUR-TOKEN'
# })

# await octokit.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
#   owner: 'OWNER',
#   repo: 'REPO',
#   workflow_id: 'WORKFLOW_ID',
#   ref: 'topic-branch',
#   inputs: {
#     name: 'Mona the Octocat',
#     home: 'San Francisco, CA'
#   },
#   headers: {
#     'X-GitHub-Api-Version': '2022-11-28'
#   }
# })

      - name: list files on the state directory
        # working-directory: ./state
        if: always()
        run: ls -la

      - name: end of build
        run: |
          # Add your build and deploy commands here
          echo "end of build"
      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifacts
      #     path: ./state 


  # execute:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     # - name: Checkout code
  #     #   uses: actions/checkout@v3  # Updated to v3
  #     #   with:
  #     #     repository: 'IanOliv/state'
  #     #     ref: 'src'
  #     #     token: ${{ secrets.TOKEN }}
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: build-artifacts
  #         path: ./state 
  #     - name: list files on the state directory
  #       working-directory: ./state
  #       if: always()
  #       run: |
  #         # Add your build and deploy commands here
  #         ls -la
  #         echo "list files on the state directory"    
  #     - name: check python version
  #       working-directory: ./state
  #       run: |
  #         # python -m venv venv
  #         # source venv/bin/activate
  #         # pip install -r requirements.txt
  #         # python --version
  #         # python -m venv venv
  #         # pip freeze
  #         python src/main.py



        