name: My-Subworkflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Build and deploy
        run: |
          # Add your build and deploy commands here
          echo "Build and deploy complete"