name: GH-APP-WORKFLOWs
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}


on:
  push:
    tags:
      - v0.0.*
    branches:
      - main
    
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: 'The name of the image'
        required: true
        default: 'my-image'
      PEM:
        description: 'The private key for the GitHub App'
        required: true
      APP_ID:
        description: 'The ID of the GitHub App'
        required: true
      INSTALLATION_ID:
        description: 'The ID of the GitHub App installation'
        required: true
      MAIN_BRANCH:
        description: 'The main branch of the repository'
        required: true
        default: 'main'

env:
  IMAGE_NAME: ${{ github.repository }}
  TOKEN: ${{ secrets.TOKEN }}
  MAIN_BRANCH: ${{ secrets.MAIN_BRANCH }}
  GH_APP_ID: ${{ secrets.GH_APP_ID }}
  GH_APP_INSTALLATION_ID: ${{ secrets.GH_APP_INSTALLATION_ID }}
  GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
  GH_APP_PRIVATE_KEY_PATH: ${{ secrets.GH_APP_PRIVATE_KEY_PATH }}
  GH_APP_CLIENT_ID: ${{ secrets.GH_APP_CLIENT_ID }}
  GH_APP_CLIENT_SECRET: ${{ secrets.GH_APP_CLIENT_SECRET }}
  





jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v3
        with:
          repository: 'IanOliv/state'
          ref: 'src'
          token: ${{ secrets.TOKEN }}
          path: ./state
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v3
        with:
          token: ${{ secrets.TOKEN }}
          

      - name: List repository files
        uses: ./.github/actions/gh-app-script
        with:
          repo: 'state'
          path: 'from-action-1.json'
          message: 'chore: update state'
          branch: 'main-1'
          content: |
            {
              "state": "updated"
            }

# uses: actions/github-script@v7
#   id: my-script
          
# const octokit = new Octokit({
#   auth: 'YOUR-TOKEN'
# })

# await octokit.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
#   owner: 'OWNER',
#   repo: 'REPO',
#   workflow_id: 'WORKFLOW_ID',
#   ref: 'topic-branch',
#   inputs: {
#     name: 'Mona the Octocat',
#     home: 'San Francisco, CA'
#   },
#   headers: {
#     'X-GitHub-Api-Version': '2022-11-28'
#   }
# })

      # - name: list files on the state directory
      #   # working-directory: ./state
      #   if: always()
      #   run: ls -la

      # - name: end of build
      #   run: |
      #     # Add your build and deploy commands here
      #     echo "end of build"
