name: ApproveOps Workflow
run-name: ApproveOps Workflow by @${{ github.actor }}

on:
    issues:
        types: [opened, edited, reopened]
    issue_comment:
        types: [created, edited]

jobs:
    approve-ops:
        runs-on: ubuntu-latest

        steps:

        - name:  Checkout code
          uses: actions/checkout@v4
          with:
            fetch-tags: 0
            fetch-depth: 0


        - name: Retrieve app token
          id: app-token
          uses: ./.github/actions/gh-app-script
          with:
            app-id: ${{ secrets.GH_APP_ID }}
            private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
            installation-id: ${{ secrets.GH_APP_INSTALLATION_ID }}
        - name: patch version
          id: verision
          uses: ./.github/actions/semmantic-version
          with:
            tag-type: minor
            token: ${{ steps.app-token.outputs.token }}
            # private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
            # installation-id: ${{ secrets.GH_APP_INSTALLATION_ID }}


        - uses: actions/github-script@v7
          id: my-script
          with:
            result-encoding: string
            github-token: ${{ steps.app-token.outputs.token }}
            script: |
                console.log(context)
                github.rest.issues.addLabels({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    labels: ['Triage']
                })


        - name: Checkout code
          run: |
            echo ${{ steps.my-script.outputs.result }}
            echo '------'
            # git pull --tags
            git tag -l | sort -V
            echo '------'
            ls -la
            

        # - name: echo token
        #   run: |
        #     echo ${{ secrets.GH_APP_ID }}

        #   env:
        #     SECRET_VAR: ${{ secrets.MY_SECRET }}
        #     VAR_VAR: ${{ fromJson(secrets.MY_VAR) }}
