name: My-Subworkflow

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      is-act:
        description: 'Is this an act?'
        required: true
        default: 'false'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      is-act: ${{ steps.vars.outputs.IS_AC }}
    steps:
        - name:  Checkout code
          uses: actions/checkout@v4
          with:
            fetch-tags: 0
            fetch-depth: 0


        - name: Retrieve app token
          id: app-token
          uses: ./.github/actions/gh-app-script
          with:
            app-id: ${{ secrets.GH_APP_ID }}
            private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
            installation-id: ${{ secrets.GH_APP_INSTALLATION_ID }}
        - name: patch version
          id: verision
          uses: ./.github/actions/semmantic-version
          with:
            tag-type: stable
            token: ${{ steps.app-token.outputs.token }}
            # private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
            # installation-id: ${{ secrets.GH_APP_INSTALLATION_ID }}


        - uses: actions/github-script@v7
          id: my-script
          with:
            result-encoding: string
            github-token: ${{ steps.app-token.outputs.token }}
            script: |
                console.log(context)
                github.rest.issues.addLabels({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    labels: ['Triage']
                })


        - name: Checkout code
          run: |
            echo ${{ steps.my-script.outputs.result }}



