name: GitHub Manager Workflows
run-name:  Deploy to  ${{ github.actor }} @ ${{ github.repository }} / ${{ github.run_number }} 

on: [push]

jobs:
  generate-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        

      - name: Generate GitHub App Token
        id: generate_token
        uses: ./.github/actions/generate-token  # Use the action defined in the repository
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      # - name: Generate composite 
      #   id: generate_token_composite
      #   uses: ./.github/actions/generate-token-composite  # Use the action defined in the repository

      - name: Use GitHub cli
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: gh repo list IanOliv --limit 100 --json 'name'
  checks:
    runs-on: ubuntu-latest
    needs: generate-token
    env:
      GITHUB_TOKEN: ${{ needs.generate-token.outputs.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        

      - name: Use GitHub cli
        run: gh repo list IanOliv --limit 100 --json 'name'

