name: "Metrics Workflow"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [metrics]

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Composite Action
        uses: ./.github/actions/gh-metrics
        with:
          action: 'init'
          
      - name: Run Composite Action
        uses: ./.github/actions/gh-metrics
        with:
          action: 'end'
          
      # - name: Send time to GitHub
      #   id: send
      #   shell: bash
      #   run: |
      #     echo "## ${{ github.job }} metrics" >> $GITHUB_STEP_SUMMARY 
      #     # echo "" >> $GITHUB_SUMMARY
      #     # echo "job-init= ${{ steps.init }}" >> $GITHUB_SUMMARY
      #     # echo "job-end= ${{ steps.end }}" >> $GITHUB_SUMMARY


      
      # - name: Cache Node.js modules
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-9-${{ hashFiles('**/package-lock.json') }} 
      #     # restore-keys: |
      #     #     ${{ runner.os }}-node-

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'

      # - name: Install dependencies
      #   run: npm install

      # - name: Run tests
      #   run: npm test