name: Update Major Version on Main

on:
  push:
    branches:
      - main  # Change this if your major versioning branch is different

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Get the latest tag
        id: get_tag
        run: |
          # Fetch all tags
          git fetch --tags

          # Get the latest tag or default to v0.0.0 if no tags exist
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")

          # Split the latest tag into components
          IFS='.' read -r major minor patch <<<"${latest_tag#v}"

          # Increment the major version, and reset minor and patch versions
          major=$((major + 1))
          minor=0
          patch=0

          # Create the new tag
          new_tag="v${major}.${minor}.${patch}"
          
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Tag the commit
        run: |
          git tag ${{ env.new_tag }}

      - name: Push the new tag
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git push origin ${{ env.new_tag }}
