name: Workflow with gh cli

on:
  push:
    tags:
      - v0.0.*
  #   branches:
  #     - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: true == false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh
      - name: Authenticate GitHub CLI
        run: |
          echo ${{ secrets }} 
          echo ${{ secrets.TOKEN }} | gh auth login --with-token
      - name: install gh copilot extension
        run: |
          gh extension install github/gh-copilot
      - name: Explain gh copilot
        run: |
          gh repo list --limit 100
          gh copilot explain "sudo apt-get"
      - name: Build and deploy
        run: |
          # Add your build and deploy commands here
          echo "Build and deploy complete"
 
  prCreate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout state code
        uses: actions/checkout@v4  # Updated to v3
        with:
          repository: 'IanOliv/state'
          ref: 'src'
          token: ${{ secrets.TOKEN }}
          path: ./state
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v3
        with:
          token: ${{ secrets.TOKEN }}


      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh
      - name: Authenticate GitHub CLI
        run: |
          echo ${{ secrets }} 
          echo ${{ secrets.TOKEN }} | gh auth login --with-token

      - name: check credentials lookin for repos
        run: |
          gh repo list --limit 100
      - name: Create a PR
        # working-directory: /home/runner/work/reusable-workflows/state
        run: |
          gh pr create --base main --head new-branch --title "My PR title" --body "My PR body" --repo IanOliv/state
    